version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: geologiya_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/geologiya_db
      SECRET_KEY: ваш_секретный_ключ
    depends_on:
      - db

volumes:
  postgres_data: