version: '3.8'

services:
  db:
    image: postgres:13.10
    env_file: .env.production
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - webnet
  backend:
    image: docker.io/pochek/geology_backend:latest  # Используем готовый образ
    env_file: .env.production
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn geology.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    depends_on:
      - db
    restart: always
    networks:
      - webnet
  nginx:
    image: docker.io/pochek/geology_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/geology.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - static_volume:/app/collected_static
      - media_volume:/app/media
    depends_on:
      - backend
    restart: always
    networks:
      - webnet
    command: >
        sh -c "rm -f /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  webnet:

