#version: '3.8'
#
#services:
#  db:
#    image: postgres:13.10
#    environment:
#      POSTGRES_DB: geology_dev
#      POSTGRES_USER: django_dev
#      POSTGRES_PASSWORD: dev_password
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    environment:
#      DEBUG: "True"
#      DB_HOST: db
#      POSTGRES_DB: geology_dev
#      POSTGRES_USER: django_dev
#      POSTGRES_PASSWORD: dev_password
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#
#volumes:
#  postgres_data:
#  static:
#  media:

version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./geology_backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  nginx:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 9000:80
