version: '3.8'

services:
  db:
    image: postgres:13.10
    env_file: .env.production
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: docker.io/pochek/geology_backend:latest
    env_file: .env.production
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn geology.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/app/collected_static  # Тот же путь что и в nginx
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: docker.io/pochek/geology_nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/collected_static  # Исправлено на тот же путь
    depends_on:
      - backend
volumes:
  pg_data:
  static_volume: