version: '3.8'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always

  backend:
    image: pochek/geology_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:9000 --timeout 120 geology.wsgi"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: pochek/geology_nginx
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - static_volume:/staticfiles:ro
      - media_volume:/media:ro
    ports:
      - "80:80"
    restart: always

