# Generated by Django 4.2 on 2025-06-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_link',
        ),
    ]
