# Generated by Django 4.2 on 2025-06-11 13:46

import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/', validators=[api.validators.validate_image_extension, api.validators.validate_image_size, api.validators.validate_svg_content], verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, help_text='Используется как основное в списках товаров', verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Новая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар распродажи',
                'verbose_name_plural': 'Товары распродажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sale_items/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, help_text='Используется как основное в списках товаров', verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.saleitem', verbose_name='Товар распродажи')),
            ],
            options={
                'verbose_name': 'Изображение товара распродажи',
                'verbose_name_plural': 'Изображения товаров распродажи',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='armament',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вооружение'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='product',
            name='iadc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IADC'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='seal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уплотнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=100, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thread_connection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Присоединительная резьба'),
        ),
        migrations.AddField(
            model_name='product',
            name='thread_connection_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Присоединительная резьба 2'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', validators=[api.validators.validate_image_extension, api.validators.validate_image_size, api.validators.validate_svg_content], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='positions',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.TextField(blank=True, verbose_name='Должности'),
        ),
    ]
