# Generated by Django 4.2 on 2025-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_options_remove_employee_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='positions',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.TextField(blank=True, verbose_name='Должности'),
        ),
    ]
