# Generated by Django 4.2 on 2025-07-05 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fix_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='Цена в рублях. Минимальное значение: 0.01', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
