# Generated by Django 4.2 on 2025-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=list, verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
