name: Deploy Backend

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: server290.hosting.reg.ru
          username: u3143616
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/u3143616/data/www/geologiya-ru.ru/geology_backend
            docker-compose down
            docker-compose up -d --build
