name: Deploy

# Добавьте секцию "on" с указанием событий
on:
  push:
    branches:
      - dev  # Workflow запустится при пуше в ветку dev
  pull_request:
    branches:
      - dev  # Или при создании pull request в ветку dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes
        run: git push origin dev
