name: Deploy Backend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'nginx/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:latest

    - name: Build and push nginx image
      uses: docker/build-push-action@v3
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/geology_nginx:latest

    - name: Deploy to backend server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.BACKEND_SERVER_IP }}  # 83.166.245.78
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/geology_backend
          git pull origin main
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/geology_nginx:latest
          docker compose down
          docker compose up -d
          docker compose exec backend python manage.py migrate --noinput
          docker compose exec backend python manage.py collectstatic --noinput