name: Deploy Django to Reg.ru

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "=== Начало деплоя ==="
            
            # Остановить сервисы
            sudo systemctl stop gunicorn || true
            
            # Основные пути
            ROOT_DIR="/var/www/u3143616/data/www/geologiya-ru.ru"
            PROJECT_DIR="$ROOT_DIR/geology_backend"
            
            # Очистка корневой директории (кроме geology_backend)
            echo "Очистка старой версии..."
            cd $ROOT_DIR
            find . -maxdepth 1 ! -name 'geology_backend' ! -name . -exec rm -rf {} +
            
            # Обновление кода в целевой директории
            if [ -d "$PROJECT_DIR" ]; then
              cd $PROJECT_DIR
              git fetch --all
              git reset --hard origin/dev
              git clean -fd
            else
              git clone https://github.com/Andrey-0367/geology_backend.git -b dev $PROJECT_DIR
            fi
            
            # Переход в директорию проекта
            cd $PROJECT_DIR
            
            # Обновление виртуального окружения
            if [ ! -d "myenv" ]; then
              python -m venv myenv
            fi
            source myenv/bin/activate
            pip install -r requirements.txt
            
            # Настройка окружения
            echo "SECRET_KEY='django-insecure-t#%1o_#!1*2b+3&phkx5yp1((26zo(av6v9#0%4jbgb4fi9j*!'" > .env
            echo "DEBUG=False" >> .env
            echo "ALLOWED_HOSTS=geologiya-ru.ru,31.31.197.37,localhost" >> .env
            # Добавьте другие переменные
            
            # Миграции и статика
            python manage.py migrate
            python manage.py collectstatic --noinput
            
            # Права доступа
            sudo chown -R u3143616:www-data $ROOT_DIR
            sudo find $ROOT_DIR -type d -exec chmod 775 {} \;
            sudo find $ROOT_DIR -type f -exec chmod 664 {} \;
            
            # Перезапуск сервисов
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            
            echo "=== Деплой успешно завершен ==="