- name: Deploy to server
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.SERVER_IP }}
    port: ${{ secrets.SSH_PORT }}
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      # Убедимся, что Docker работает
      sudo systemctl start docker || true
      sudo systemctl enable docker || true
      
      # Добавим пользователя в группу docker
      sudo usermod -aG docker $USER || true
      newgrp docker || true
      
      # Перейдем в директорию проекта
      cd /opt/geology_backend
      
      # --- ИСПРАВЛЕНИЕ НАЧИНАЕТСЯ ЗДЕСЬ ---
      # Сбрасываем локальные изменения и обновляем репозиторий
      git reset --hard HEAD
      git clean -fd
      git pull origin main
      
      # Убедимся, что файлы обновились
      git status
      git log -1
      # --- ИСПРАВЛЕНИЕ ЗАКАНЧИВАЕТСЯ ЗДЕСЬ ---
      
      # Обновим контейнеры
      sudo docker compose pull
      
      # Перезапустим приложение
      sudo docker compose down
      sudo docker compose up -d
      
      # Применим миграции и соберем статику
      sudo docker compose exec -T backend python manage.py migrate --noinput
      sudo docker compose exec -T backend python manage.py collectstatic --noinput
      
      # Проверим статус контейнеров
      sudo docker compose ps
      sudo docker compose logs --tail=20
      
      # Проверим доступность админки
      echo "Проверка админки:"
      curl -I http://localhost/admin/ || true