name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:latest
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:buildcache,mode=max

    - name: Build and push nginx image
      uses: docker/build-push-action@v3
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/geology_nginx:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/geology_backend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/geology_backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/geology_nginx:latest
          docker compose down
          docker compose up -d
          docker compose exec backend python manage.py migrate --noinput
          docker compose exec backend python manage.py collectstatic --noinput