name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Логин в Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Сборка и пуш backend образа
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          docker.io/pochek/geology_backend:latest
        cache: false

    # Сборка и пуш nginx образа
    - name: Build and push nginx image
      uses: docker/build-push-action@v5
      with:
        context: nginx
        file: nginx/Dockerfile
        push: true
        tags: |
          docker.io/pochek/geology_nginx:latest
        cache: false

    # Деплой на сервер с использованием ПАРОЛЯ
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SSH_PORT }}  # Убедитесь что порт 2222 задан в секретах
        username: root
        password: ${{ secrets.SSH_PASSWORD }}  # Используем пароль
        script: |
          cd /opt/geology_backend
          docker compose pull
          docker compose down
          docker compose up -d
          docker compose exec -T backend python manage.py migrate --noinput
          docker compose exec -T backend python manage.py collectstatic --noinput