name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          docker.io/pochek/geology_backend:latest
        cache: false

    - name: Build and push nginx image
      uses: docker/build-push-action@v5
      with:
        context: nginx
        file: nginx/Dockerfile
        push: true
        tags: |
          docker.io/pochek/geology_nginx:latest
        cache: false

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/geology_backend
          git pull origin main
          
          sudo docker compose down
          sudo docker compose pull
          sudo docker compose up -d
          
          sleep 10  # Дать контейнерам время на запуск
          
          sudo docker compose exec -T backend python manage.py migrate --noinput
          sudo docker compose exec -T backend python manage.py collectstatic --noinput
          
          # Проверка доступности админки
          curl -I http://localhost/admin/login/ || echo "Admin check failed"