name: Deploy
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Reg.ru
      uses: appleboy/ssh-action@master
      with:
        host: 31.31.197.37
        username: u3143616
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/u3143616/data/www/geologiya-ru.ru
          git pull origin dev