- name: Deploy via SSH
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    script: |
      echo "Деплой начался..."
      cd /var/www/geologiya-ru.ru
      git pull origin dev
      source myenv/bin/activate
      pip install -r requirements.txt
      python manage.py migrate
      sudo systemctl restart gunicorn