name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Docker Hub access
      run: |
        echo "Проверка доступа к Docker Hub"
        curl -u "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" \
          "https://hub.docker.com/v2/repositories/pochek/geology_backend/" || true
        curl -u "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" \
          "https://hub.docker.com/v2/repositories/pochek/geology_nginx/" || true
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: pochek/geology_backend:latest
        cache: false  # Отключите кэш для диагностики

    - name: Build and push nginx image
      uses: docker/build-push-action@v5
      with:
        context: nginx
        file: nginx/Dockerfile
        push: true
        tags: pochek/geology_nginx:latest
        cache: false  # Отключите кэш для диагностики

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/geology_backend
          docker compose pull
          docker compose down
          docker compose up -d
          docker compose exec -T backend python manage.py migrate --noinput
          docker compose exec -T backend python manage.py collectstatic --noinput